version: '2'
services:
    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
    kafka:
      image: robinschuerer/kafka
      ports:
            - 9092:9092
      volumes:
            - ./config:/config
            - ./logs:/kafka-logs
